### ISSUE TITLE
보석 정보 오류

### ISSUE THREAD

**Issue by Reuhania** [knsan189/gibbet-finder#1]
장착된 보석에 마우스를 올렸을 경우 올바른 정보가 출력 되지 않는 현상
(다른 칸에 있는 보석의 정보가 뒤바뀌어 출력 됨)

**Comment by knsan189** [comment]
아 스킬정보랑 보석 이미지랑 인덱스가 안맞나 보네 바로 수정할게요

**Comment by Reuhania** [comment]
추가로 보석칸에 10홍 배경색이 초록색으로 표기되는 문제가 있습니다.
